on: release
name: Build
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile and release
      uses: bcambl/go-release.action@v1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        GOARCH: amd64
        GOOS: linux
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile and release
      uses: bcambl/go-release.action@v1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        GOARCH: amd64
        GOOS: windows